language: node_js

branches:
  only:
    - master
    
node_js: '8'
cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install
  
before_script:
  - yarn test
  
before_cache:
  - rm -rf ./node_modules/gh-pages-with-token/node_modules/gh-pages/.cache
  
script:
  - yarn build:logo
  - yarn build
  - echo "$CNAME" > build/CNAME
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ];then yarn deploy:travis; fi
  - yarn test:lh https://$CNAME/
